dist: trusty

language: node_js
node_js:
  - 'node'

branches:
  only:
    - master

script:
  - npm run lint
  - npm run test
  - npm run build:lib
  - npm run deploy:build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/ng-mat-icons-app
  on:
    branch: master
